### ISSUE TITLE
Bug: 4.4.9 invalid argument

### ISSUE THREAD

**Issue by bergerar** [contao/comments-bundle#10] opened 2017-12-17 16:11 UTC
$arrOptions is passed to Contao\Model::isPreviewMode(array $arrOptions), but $arrOptions isn't set in this function.

`Type error: Argument 1 passed to Contao\Model::isPreviewMode() must be of the type array, null given, called in \vendor\contao\comments-bundle\src\Resources\contao\models\CommentsModel.php on line 149`

PHP 7.1

**Comment by fritzmg** [comment] 2017-12-17 16:29
Duplicate of #9

**Closed as completed** 2017-12-17 16:40 UTC
Labels: duplicate
